"""Baseline: the schema as it stood before Alembic was introduced.

Fresh databases get every table from this revision. An EXISTING database is
adopted with `alembic stamp 0001_baseline` — never by running this upgrade,
which would fail on tables that already exist. See docs/DEPLOY.md.

Original autogenerate header

Revision ID: fcdb15f60eed
Revises: 
Create Date: 2026-08-01 10:34:14.991454
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_slug'), ['slug'], unique=True)

    op.create_table('api_check_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('stat_xp_awarded', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_completions_habit_id'), ['habit_id'], unique=False)

    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('base_xp_reward', sa.Integer(), nullable=False),
    sa.Column('stat_rewards', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('duration_size', sa.String(length=20), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_key', sa.String(length=50), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hero_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_stats_stat_key'), ['stat_key'], unique=True)

    op.create_table('japanese_save_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save_date', sa.Date(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('wanikani_level', sa.Integer(), nullable=False),
    sa.Column('bunpro_level', sa.String(length=20), nullable=True),
    sa.Column('bunpro_points', sa.Integer(), nullable=False),
    sa.Column('source_character_level', sa.Integer(), nullable=False),
    sa.Column('source_character_rank', sa.String(length=100), nullable=True),
    sa.Column('source_level_xp', sa.Integer(), nullable=False),
    sa.Column('source_level_xp_cap', sa.Integer(), nullable=False),
    sa.Column('reported_session_xp', sa.Integer(), nullable=True),
    sa.Column('vocabulary_score', sa.Integer(), nullable=False),
    sa.Column('grammar_score', sa.Integer(), nullable=False),
    sa.Column('reading_score', sa.Integer(), nullable=False),
    sa.Column('listening_score', sa.Integer(), nullable=False),
    sa.Column('speaking_score', sa.Integer(), nullable=False),
    sa.Column('current_grammar_point', sa.String(length=200), nullable=True),
    sa.Column('debuffs_text', sa.Text(), nullable=True),
    sa.Column('new_vocabulary_text', sa.Text(), nullable=True),
    sa.Column('daily_quest_text', sa.Text(), nullable=True),
    sa.Column('raw_save', sa.Text(), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('session_mode', sa.String(length=20), nullable=True),
    sa.Column('session_completion', sa.String(length=20), nullable=True),
    sa.Column('reward_calculation', sa.String(length=30), nullable=True),
    sa.Column('stat_xp_awarded', sa.Integer(), nullable=False),
    sa.Column('stat_rewards', sa.Text(), nullable=True),
    sa.Column('warning_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('japanese_save_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_japanese_save_imports_normalized_hash'), ['normalized_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_japanese_save_imports_save_date'), ['save_date'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('match_text', sa.String(length=200), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('stat_rewards', sa.Text(), nullable=True),
    sa.Column('attribute', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('duration_size', sa.String(length=20), nullable=True),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_slug'), ['slug'], unique=True)

    op.create_table('stat_xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_key', sa.String(length=50), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_xp_events_stat_key'), ['stat_key'], unique=False)

    op.create_table('sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_source_id'), ['source_id'], unique=False)

    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_events')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_source_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('stat_xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_xp_events_stat_key'))

    op.drop_table('stat_xp_events')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_slug'))

    op.drop_table('quests')
    with op.batch_alter_table('japanese_save_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_japanese_save_imports_save_date'))
        batch_op.drop_index(batch_op.f('ix_japanese_save_imports_normalized_hash'))

    op.drop_table('japanese_save_imports')
    with op.batch_alter_table('hero_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_stats_stat_key'))

    op.drop_table('hero_stats')
    op.drop_table('hero_profile')
    op.drop_table('habits')
    with op.batch_alter_table('habit_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_completions_habit_id'))

    op.drop_table('habit_completions')
    op.drop_table('api_check_events')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_slug'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
