"""Goals plus optional goal links on habits and quests.

Purely additive. The new NOT NULL columns carry a server_default so existing
rows get a value instead of the migration failing on a populated table.

Original autogenerate header

Revision ID: 7633fa1c2cf2
Revises: 0001_baseline
Create Date: 2026-08-01 11:54:35.112622
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_goals'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_habits_goal_id'), ['goal_id'], unique=False)

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('is_milestone', sa.Boolean(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_quests_goal_id'), ['goal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_goal_id'))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_milestone')
        batch_op.drop_column('goal_id')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_goal_id'))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('goal_id')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_status'))
        batch_op.drop_index(batch_op.f('ix_goals_slug'))

    op.drop_table('goals')
    # ### end Alembic commands ###
