"""Append-only quest completions plus a stable habit link on quests.

Purely additive. quests.habit_id is nullable, so existing quests keep using
match_text. No historical completions are invented: the table starts empty and
quests already finished before this revision simply have no row (see
docs/ROADMAP.md for the cutover behaviour).

Original autogenerate header

Revision ID: ace0cc174054
Revises: 0002_goals
Create Date: 2026-08-01 12:33:10.461241
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_quest_completions'
down_revision: Union[str, None] = '0002_goals'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('stat_xp_awarded', sa.Integer(), nullable=False),
    sa.Column('stat_rewards', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_completions_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_quest_completions_quest_id'), ['quest_id'], unique=False)

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habit_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quests_habit_id'), ['habit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_habit_id'))
        batch_op.drop_column('habit_id')

    with op.batch_alter_table('quest_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_completions_quest_id'))
        batch_op.drop_index(batch_op.f('ix_quest_completions_dedup_key'))

    op.drop_table('quest_completions')
    # ### end Alembic commands ###
